[32mCreateUsersTable:[39m create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `isAdmin` tinyint(1) null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
[32mCreateUsersTable:[39m alter table `users` add unique `users_email_unique`(`email`)
[32mCreatePasswordResetsTable:[39m create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
[32mCreatePasswordResetsTable:[39m alter table `password_resets` add index `password_resets_email_index`(`email`)
[32mCreateFailedJobsTable:[39m create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
[32mCreateFailedJobsTable:[39m alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`)
[32mCreateLibrosTable:[39m create table `libros` (`id` bigint unsigned not null auto_increment primary key, `titolo` varchar(255) not null, `edizione` varchar(255) null, `autore` varchar(255) not null, `categoria` varchar(255) null, `anno_publicazione` varchar(255) null, `img_path` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
[32mCreateCopiasTable:[39m create table `copias` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `disponibile` tinyint(1) not null, `libro_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
[32mCreateCopiasTable:[39m alter table `copias` add constraint `copias_libro_id_foreign` foreign key (`libro_id`) references `libros` (`id`)
[32mCreatePrestitosTable:[39m create table `prestitos` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `data_fine` timestamp null, `restituito` tinyint(1) not null default '0', `copia_id` bigint unsigned not null, `user_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
[32mCreatePrestitosTable:[39m alter table `prestitos` add constraint `prestitos_copia_id_foreign` foreign key (`copia_id`) references `copias` (`id`)
[32mCreatePrestitosTable:[39m alter table `prestitos` add constraint `prestitos_user_id_foreign` foreign key (`user_id`) references `users` (`id`)
